### ISSUE TITLE
Transforming quadratic systems into matrix form

### ISSUE THREAD

**Issue by mforets** [JuliaReach/CarlemanLinearization.jl#11]

**Comment by pogudingleb** [comment]
Here is how I would imagine this working:
```julia
using DynamicPolynomials
@polyvar x y
F1, F2 = get_linear_square_parts([
    (x, x + y^2),
    (y, x - y + x * y + x^2)
])
```
where, in each tuple, the first entry is a variable and the second is the corresponding right-hand side. For example, the input above would describe the ODE system
```
x' = x + y^2
y' = x - y + x * y + x^2
```
